### PR TITLE
add direct dependency on simple-get

### PR DESCRIPTION
**Pull request by macfarla**
To address dependabot alert

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

### CODE REVIEW

**Review by frankisawesome — COMMENTED** [review]
There's a really big diff in yarn.lock, is this expected from one dependency change?

**Comment by macfarla** [comment]
> There's a really big diff in yarn.lock, is this expected from one dependency change?

yeah sometimes that happens

**Comment by macfarla** [comment]
one thing that has changed is

**Comment by macfarla** [comment]
-    "graphql-tag" "^2.12.3"
-    "hoist-non-react-statics" "^3.3.2"
-    "optimism" "^0.16.1"
-    "prop-types" "^15.7.2"
-    "symbol-observable" "^4.0.0"
-    "ts-invariant" "^0.9.4"
-    "tslib" "^2.3.0"
-    "zen-observable-ts" "^1.2.0"
+    graphql-tag "^2.12.3"
+    hoist-non-react-statics "^3.3.2"
+    optimism "^0.16.1"
+    prop-types "^15.7.2"
+    symbol-observable "^4.0.0"
+    ts-invariant "^0.9.4"
+    tslib "^2.3.0"
+    zen-observable-ts "^1.2.0"

**Comment by macfarla** [comment]
yarn -v
1.22.10

**Comment by macfarla** [comment]
but the function of yarn.lock is just so that anyone else will get the same versions of dependencies so it doesn't really matter about the formatting

**Review by frankisawesome — APPROVED** [review]

**Comment by frankisawesome** [comment]
I think I don't have reviewer rights on this repo haha

**Pull request merged**
